[package]
name = "storage-node"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["multipart", "ws"] }
base64 = "0.22.1"
futures = "0.3.32"
hex = "0.4"
libp2p = { version = "0.53", features = ["macros", "tokio", "quic", "request-response", "cbor", "identify", "gossipsub", "kad", "mdns", "tcp", "noise", "yamux"] }
prost = "0.13"
reed-solomon-erasure = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
shared-proto = { version = "0.1.0", path = "../shared-proto" }
sled = "0.34"
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["net"] }
tonic = "0.12"
tower-http = { version = "0.6", features = ["cors"] }
