services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: feedo_admin
      POSTGRES_PASSWORD: secure_password_here
      POSTGRES_DB: feedo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedo_admin -d feedo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  feedo_node:
    image: itsshas/feedo-node:latest
    restart: always
    ports:
      - "8040:8040" 
      - "4001:4001/udp" 
    environment:
      - DATABASE_URL=postgresql+asyncpg://feedo_admin:secure_password_here@db:5432/feedo_db
      
      - RSS_NODE_WALLET=your_node_wallet_public_did
      - RSS_NODE_SECRET=your_node_secret_seed_phrase

      - RUST_CORE_URL=http://127.0.0.1:8041/local/publish
      - PYTHON_API_URL=http://127.0.0.1:8040
      
      - DHT_DB_PATH=/app/db/rust_store
      - DHT_RAM_CACHE_LIMIT=1000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - rust_db_data:/app/db

volumes:
  postgres_data:
  rust_db_data:
