import base64
import os
import logging
import json as _json
import asyncio
import re
import secrets
import uuid
import math
import random
import httpx
import difflib
import time
from datetime import datetime, timezone, timedelta

try:
    import feedo_pb2
except ImportError:
    pass # Generated by docker build
from fastapi import FastAPI, File, Form, HTTPException, Depends, Request, Response, UploadFile, Query
from sqlalchemy import desc, or_, and_, inspect, text, func
from sqlalchemy.exc import IntegrityError
from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from sqlalchemy.orm.attributes import flag_modified
from contextlib import asynccontextmanager
import uvicorn
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Any, List, Dict, Optional
import aiohttp
import uuid
import sys
from fastapi import WebSocket, WebSocketDisconnect
from typing import Set
from auth import validate_zero_trust_request
from auth_deps import get_api_key
from database import engine, Base, AsyncSessionLocal, ensure_postgres_database_exists
from models import Post, User, ContentType, UserKey, ApiKeyRole, Edge
from services.vector_service import VectorBrain
from core.utils.crypto_utils import verify_signature, generate_content_hash
from core.utils.content_sources.text_utils import sanitize_for_storage
# from unified_monitor import monitor_all, run_monitor_process
import threading
from admin import router as admin_router
from users import router as users_router
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("feedo_api")

from prometheus_client import Counter, Gauge, generate_latest, CONTENT_TYPE_LATEST
VECTOR_QUERIES = Counter('vector_queries_total', 'Total vector queries', ['role', 'status'])
DHT_FETCHES = Counter('dht_fetch_total', 'Total DHT fetches')
ACTIVE_REQUESTS = Gauge('current_inflight_requests', 'Current inflight requests')
LAST_BACKFILL = Gauge('last_backfill_timestamp', 'Last backfill timestamp')


RUST_CORE_URL = os.getenv("RUST_CORE_URL", "http://127.0.0.1:8041/local/publish")

default_fetch_url = RUST_CORE_URL.replace("/local/publish", "/local/fetch_content") if RUST_CORE_URL else "http://127.0.0.1:8041/local/fetch_content"
RUST_FETCH_CONTENT_URL = os.getenv("RUST_FETCH_CONTENT_URL", default_fetch_url)

RUST_FETCH_CONTENT_URLS_RAW = os.getenv("RUST_FETCH_CONTENT_URLS")
if RUST_FETCH_CONTENT_URLS_RAW:
    RUST_FETCH_CONTENT_URLS = [u.strip() for u in RUST_FETCH_CONTENT_URLS_RAW.split(",") if u.strip()]
else:
    RUST_FETCH_CONTENT_URLS = [RUST_FETCH_CONTENT_URL]

EXPOSE_VECTOR_API = True
VECTOR_API_ADDR = os.getenv("VECTOR_API_ADDR", "http://127.0.0.1:8040")
VECTOR_API_KEY = os.getenv("VECTOR_API_KEY", "")

def _require_server_variant() -> None:
    pass


MEDIA_CACHE: Dict[str, Dict[str, Any]] = {}
_default_media_cache_root = "/app/db" if os.path.isdir("/app/db") else os.path.join(".", "db_data")
MEDIA_DISK_CACHE_DIR = os.getenv(
    "MEDIA_DISK_CACHE_DIR",
    os.path.join(_default_media_cache_root, "media_cache"),
)
os.makedirs(MEDIA_DISK_CACHE_DIR, exist_ok=True)


def _media_cache_file_path(media_hash: str) -> str:
    return os.path.join(MEDIA_DISK_CACHE_DIR, media_hash)


def _load_media_from_disk_cache(media_hash: str) -> bytes | None:
    cache_path = _media_cache_file_path(media_hash)
    if not os.path.exists(cache_path):
        return None
    try:
        with open(cache_path, "rb") as media_file:
            return media_file.read()
    except Exception:
        logger.warning("Failed to read cached media from %s", cache_path, exc_info=True)
        return None


def _store_media_to_disk_cache(media_hash: str, media_bytes: bytes) -> None:
    cache_path = _media_cache_file_path(media_hash)
    try:
        with open(cache_path, "wb") as media_file:
            media_file.write(media_bytes)
    except Exception:
        logger.warning("Failed to persist media cache for %s", media_hash, exc_info=True)

brain = None
p2p = None
from aggregator import AggregatorClient

async def node_heartbeat_loop():
    await asyncio.sleep(10)
    
    node_wallet_raw = os.environ.get("RSS_NODE_WALLET")
    api_url = os.environ.get("PYTHON_API_URL")
    
    if not node_wallet_raw:
        return
    
    node_wallet = _normalize_wallet_address(node_wallet_raw)
        
    while True:
        try:
            async with AsyncSessionLocal() as db:
                posts_count = (await db.execute(select(func.count(Post.id)))).scalar() or 0
                
                stmt = select(User).where(User.wallet_address == node_wallet)
                user = (await db.execute(stmt)).scalar_one_or_none()
                if not user:
                    user = User(
                        public_id="feedo_node_" + node_wallet[:8].replace("0x", ""),
                        username="Node " + node_wallet[:6].replace("0x", ""),
                        wallet_address=node_wallet,
                        api_url=api_url,
                        indexed_posts_count=posts_count
                    )
                    db.add(user)
                else:
                    user.api_url = api_url
                    user.indexed_posts_count = posts_count
                await db.commit()
        except Exception as e:
            logger.error(f"Node heartbeat failed: {e}")
            
        await asyncio.sleep(60)

async def background_centroid_updater():
    await asyncio.sleep(60)
    is_supernode = os.getenv("IS_SUPERNODE", "false").lower() == "true"
    if not is_supernode:
        return
        
    logger.info("Роль Supernode активована. Запуск фонового генератора центроїдів...")
    last_update = 0
    
    while True:
        try:
            now = time.time()
            if not brain:
                await asyncio.sleep(60)
                continue
                
            current_count = len(brain.table.search().limit(100000).to_list())
            last_count = getattr(brain, 'last_cluster_post_count', 0)
            
            needs_update = False
            if now - last_update > 3600:
                needs_update = True
                logger.info("Планове оновлення центроїдів (1 година)...")
            elif last_count > 0 and current_count > 0:
                diff = abs(current_count - last_count) / last_count
                if diff > 0.2:
                    needs_update = True
                    logger.info(f"Event-based оновлення центроїдів (Зміна контенту {diff*100:.1f}% > 20%)...")
                    
            if needs_update:
                loop = asyncio.get_event_loop()
                centroids = await loop.run_in_executor(brain.executor, lambda: brain.compute_centroids(n_clusters=10))
                if centroids:
                    rust_url = RUST_CORE_URL.replace("/local/publish", "/local/push_centroids")
                    payload = {
                        "cluster_ids": [f"cluster_{i}" for i in range(len(centroids))],
                        "centroids": centroids
                    }
                    async with httpx.AsyncClient() as client:
                        resp = await client.post(rust_url, json=payload, timeout=10.0)
                        if resp.status_code == 200:
                            logger.info("Успішно передано локальні центроїди до Rust-ядра для трансляції.")
                    last_update = now
        except Exception as e:
            logger.error(f"Error in centroid updater: {e}")
            
        await asyncio.sleep(60)

async def background_stats_updater():
    await asyncio.sleep(10)
    while True:
        try:
            async with AsyncSessionLocal() as session:
                total_posts = await session.scalar(select(func.count(Post.id))) or 0
                rust_url = os.environ.get("RUST_CORE_URL", "http://127.0.0.1:8041/local/publish")
                stats_url = rust_url.replace("/local/publish", "/local/set_stats")
                async with httpx.AsyncClient() as client:
                    await client.post(stats_url, json={"indexed_posts": total_posts}, timeout=5.0)
        except Exception as e:
            logger.warning(f"Failed to update stats in Rust core: {e}")
        await asyncio.sleep(60)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global brain
    brain = VectorBrain() 

    await ensure_postgres_database_exists()
    
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        await conn.run_sync(_ensure_users_schema_columns)

    # Запускаємо міграції в окремій транзакції, щоб помилка не скасувала створення таблиць
    async with engine.begin() as conn:
        try:
            logger.info("Міграція адрес з префіксом 04 (виправлення старих записів)...")
            
            # Helper function to run update only if table exists
            async def update_if_exists(table_name, column_name):
                # We check if table exists before updating
                import sqlalchemy
                inspector = sqlalchemy.inspect(conn.sync_engine) if hasattr(conn, 'sync_engine') else None
                # Or just catch exception per statement to avoid transaction aborts
                # In asyncpg, if a statement fails, the transaction is aborted. 
                # To be safe, we can just use savepoints or check existence.
                pass
            
            tables = [
                ("posts", "author_address"),
                ("interactions", "wallet_address"),
                ("relationships", "user_a"),
                ("relationships", "user_b"),
                ("relationships", "requester"),
                ("follows", "follower_wallet"),
                ("follows", "target_wallet"),
                ("users", "wallet_address"),
                ("notifications", "recipient_wallet"),
                ("notifications", "source_wallet"),
            ]
            
            # Since some tables might not exist, we just check if they exist first.
            def _check_table(sync_conn, table):
                return sqlalchemy.inspect(sync_conn).has_table(table)
            
            import sqlalchemy
            
            for table, col in tables:
                exists = await conn.run_sync(lambda sync_conn, t=table: sqlalchemy.inspect(sync_conn).has_table(t))
                if exists:
                    await conn.execute(text(f"UPDATE {table} SET {col} = LOWER(SUBSTR({col}, 3)) WHERE LENGTH({col}) = 130 AND {col} LIKE '04%'"))
        except Exception as e:
            logger.warning(f"Не вдалося виконати міграцію префіксів 04: {e}")

    node_type = os.getenv("NODE_TYPE", "unified").lower()
    monitor_stop_event = threading.Event()
    
    if node_type != "proxy":
        logger.info(f"Starting background monitor process (NODE_TYPE={node_type})")
        # monitor_thread = threading.Thread(target=lambda: run_monitor_process(monitor_stop_event), daemon=True)
        # monitor_thread.start()
    else:
        logger.info("Running in PROXY mode. Background monitor process is disabled.")
    
    asyncio.create_task(node_heartbeat_loop())
    asyncio.create_task(background_centroid_updater())
    asyncio.create_task(background_stats_updater())
    
    try:
        BOOTSTRAP_NODES_RAW = os.getenv("BOOTSTRAP_NODES", "")
        BOOTSTRAP_NODES = [s.strip() for s in BOOTSTRAP_NODES_RAW.split(",") if s.strip()]
    except Exception as e:
        pass
    app.state.brain = brain
    
    yield
    
    logger.info("Зупинка фонового парсера (thread)...")
    try:
        monitor_stop_event.set()
        monitor_thread.join(timeout=5)
        logger.info("Фоновий парсер (thread) зупинено.")
    except Exception as e:
        logger.warning(f"Не вдалось коректно зупинити монітор: {e}")

    if brain is not None and getattr(brain, "executor", None) is not None:
        brain.executor.shutdown(wait=False)
    await engine.dispose()


app = FastAPI(title="Feedo P2P Gateway", lifespan=lifespan)

import os
os.makedirs("static", exist_ok=True)
os.makedirs("templates", exist_ok=True)
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

from fastapi.responses import HTMLResponse

@app.get("/dashboard", response_class=HTMLResponse, tags=["Web UI"])
async def get_dashboard(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

from api_v1.router import api_v1_router
from api_v1.wallet import router as wallet_router
from api_v1.treasury import router as treasury_router

app.include_router(api_v1_router, prefix="/v1")
app.include_router(wallet_router, prefix="/v1/wallet", tags=["Wallet"])
app.include_router(treasury_router, prefix="/v1/treasury", tags=["Treasury"])

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


from pydantic import BaseModel

async def get_db():
    async with AsyncSessionLocal() as session:
        yield session

@app.get("/explorer/stats")
async def get_explorer_stats(db: AsyncSession = Depends(get_db)):
    active_nodes = 1
    network_health = "Healthy"

    try:
        rust_url = os.environ.get("RUST_CORE_URL", "http://127.0.0.1:8041/local/publish")
        base_rust_url = rust_url.rsplit("/local/", 1)[0]
        network_info_url = f"{base_rust_url}/local/network_info"
        async with aiohttp.ClientSession() as session:
            async with session.get(network_info_url, timeout=2.0) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    if data:
                        active_nodes = data.get("total_nodes", 1)
                        network_health = "Healthy" if active_nodes > 1 else "Syncing"
    except Exception as e:
        logger.warning(f"Failed to fetch stats from Rust core: {e}")

    total_posts = await db.scalar(select(func.count(Post.id))) or 0

    return {
        "active_nodes": active_nodes,
        "indexed_posts": total_posts,
        "network_health": network_health
    }


def _normalize_wallet_address(wallet_address: str) -> str:
    cleaned = wallet_address.strip().lower()
    if cleaned.startswith('0x'):
        cleaned = cleaned[2:]
    if len(cleaned) == 130 and cleaned.startswith('04'):
        cleaned = cleaned[2:]
    return cleaned


async def _load_user_by_wallet(db: AsyncSession, wallet_address: str | None) -> User | None:
    if not wallet_address:
        return None

    normalized = _normalize_wallet_address(wallet_address)
    wallet_variants = (normalized, f"0x{normalized}")
    stmt = select(User).where(func.lower(User.wallet_address).in_(wallet_variants))
    return (await db.execute(stmt)).scalar_one_or_none()


def _display_author_name(author: User | None, original_name: str | None = None, fallback_wallet: str | None = None) -> str:
    if author is not None:
        for value in (author.display_name, author.username):
            if isinstance(value, str) and value.strip():
                return value.strip()
                
    if original_name and isinstance(original_name, str) and original_name.strip():
        return original_name.strip()
        
    if author is not None and author.public_id:
        return author.public_id
        
    if fallback_wallet:
        return fallback_wallet
    return "Unknown Node"


def _author_avatar_url(author: User | None) -> str | None:
    if author is None or not getattr(author, "avatar_media_hash", None):
        return None
    amh = author.avatar_media_hash
    if amh.startswith("http://") or amh.startswith("https://"):
        return amh
    return f"/p2p-media/{amh}"


async def _serialize_post_for_client(db: AsyncSession, post: Post) -> dict[str, Any]:
    author = post.author or await _load_user_by_wallet(db, post.author_address)
    display_author = _display_author_name(author, post.original_author_name, post.author_address)


    also_posted_by = []
    for dup in post.duplicates:
        dup_author_obj = dup.author or await _load_user_by_wallet(db, dup.author_address)
        dup_author = dup.original_author_name if dup.original_author_name else _display_author_name(dup_author_obj, dup.author_address)
        also_posted_by.append({
            "id": dup.id,
            "source_type": dup.source_type,
            "link": dup.external_link,
            "published_at": dup.published_at,
            "metadata": dup.metadata_,
            "text": dup.text_content,
            "display_author": dup_author,
            "author_address": dup.author_address,
            "avatar_url": _author_avatar_url(dup_author_obj),
            "is_repost": dup.is_repost,
        })

    item_type = post.item_type or ("profile" if (post.metadata_ and isinstance(post.metadata_, dict) and post.metadata_.get("kind") == 0) else "post")

    text = post.text_content
    if item_type == "profile" and text:
        try:
            import json
            parsed = json.loads(text)
            text = parsed.get("about", "")
        except:
            pass

    return {
        "id": post.id,
        "title": post.title,
        "hash_id": post.hash_id,
        "content_blob_hash": post.content_blob_hash,
        "prev_post_hash": post.prev_post_hash,
        "sequence_number": post.sequence_number,
        "signature": post.signature,
        "author_address": post.author_address,
        "display_author": display_author,
        "source_type": post.source_type,
        "item_type": item_type,
        "text": text,
        "content_size": post.content_size,
        "is_full": post.is_full_content_loaded,
        "published_at": post.published_at,
        "is_finalized": post.is_finalized,
        "is_verified": post.is_verified,
        "is_repost": post.is_repost,
        "metadata": post.metadata_,
        "also_posted_by": also_posted_by,
        "avatar_url": _author_avatar_url(author),
        "relay_urls": [post.relay_url] if getattr(post, "relay_url", None) else [],
    }





def _ensure_users_schema_columns(sync_conn) -> None:
    inspector = inspect(sync_conn)
    if not inspector.has_table("users"):
        Base.metadata.create_all(bind=sync_conn)
        inspector = inspect(sync_conn)

    columns = {column["name"] for column in inspector.get_columns("users")}
    if "public_id" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN public_id VARCHAR"))

        user_rows = sync_conn.execute(text("SELECT id FROM users")).fetchall()
        for row in user_rows:
            sync_conn.execute(
                text("UPDATE users SET public_id = :public_id WHERE id = :id"),
                {"id": row.id, "public_id": f"user_{uuid.uuid4().hex[:8]}"},
            )

        sync_conn.execute(
            text("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_public_id ON users (public_id)")
        )

        if sync_conn.dialect.name != "sqlite":
            sync_conn.execute(text("ALTER TABLE users ALTER COLUMN public_id SET NOT NULL"))

    if "privacy" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN privacy VARCHAR(20) DEFAULT 'everyone'"))
        columns.add("privacy")

        if sync_conn.dialect.name != "sqlite":
            sync_conn.execute(text("ALTER TABLE users ALTER COLUMN privacy SET NOT NULL"))

    if "api_url" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN api_url VARCHAR"))
        
    if "indexed_posts_count" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN indexed_posts_count INTEGER DEFAULT 0"))
        
    if "user_vector" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN user_vector JSON"))
        
    if "last_vector_updated_at" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN last_vector_updated_at TIMESTAMP WITH TIME ZONE"))
        
    if "is_admin" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN is_admin BOOLEAN DEFAULT FALSE"))
        
    if "preferred_tags" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN preferred_tags JSON DEFAULT '[]'::json"))
    else:
        # Check type and fix if it's an array from previous buggy migration
        try:
            with sync_conn.begin_nested():
                sync_conn.execute(text("ALTER TABLE users ALTER COLUMN preferred_tags TYPE JSON USING array_to_json(preferred_tags)"))
        except Exception:
            pass # Already JSON or cast failed
            
    if "preferred_languages" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN preferred_languages JSON DEFAULT '[]'::json"))
    else:
        try:
            with sync_conn.begin_nested():
                sync_conn.execute(text("ALTER TABLE users ALTER COLUMN preferred_languages TYPE JSON USING array_to_json(preferred_languages)"))
        except Exception:
            pass
        
    if "saved_chats" not in columns:
        sync_conn.execute(text("ALTER TABLE users ADD COLUMN saved_chats JSON DEFAULT '[]'::json"))

    if "privacy" in columns:
        sync_conn.execute(
            text("UPDATE users SET privacy = LOWER(privacy) WHERE privacy IS NOT NULL AND privacy != LOWER(privacy)")
        )
        sync_conn.execute(
            text("UPDATE users SET privacy = 'everyone' WHERE privacy IS NULL")
        )


def _to_naive_utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value
    return value.astimezone(timezone.utc).replace(tzinfo=None) 


async def _make_unique_username(db: AsyncSession, base_username: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", base_username).strip("_") or "user"
    candidate = normalized
    suffix = 1

    while True:
        stmt = select(User).where(User.username == candidate)
        existing = (await db.execute(stmt)).scalar_one_or_none()
        if not existing:
            return candidate
        candidate = f"{normalized}_{suffix}"
        suffix += 1


async def _seed_user_vector(user_id: int, tags_text: str):
    if not tags_text:
        return

    try:
        vector = await brain.get_embedding_async(tags_text)
        async with AsyncSessionLocal() as session:
            user = await session.get(User, user_id)
            if not user:
                return
            user.user_vector = vector
            await session.commit()
    except Exception as e:
        logger.warning(f"Не вдалося фоново побудувати вектор користувача {user_id}: {e}")


async def _background_add_vector(*args, **kwargs):
    try:
        if brain:
            await brain.add_vector_async(*args, **kwargs)
    except Exception as e:
        logger.error(f"Error in background vectorization: {e}")

async def process_incoming_post(db: AsyncSession, p_data: dict, check_chain: bool = True):
    p_data["text_content"] = sanitize_for_storage(p_data.get("text_content", ""))
    if p_data.get("title"):
        p_data["title"] = sanitize_for_storage(p_data.get("title", ""))

    if not p_data["text_content"] or brain.is_gibberish(p_data["text_content"]):
        return None

    author_address = p_data.get("author_address")
    if author_address:
        author_address = _normalize_wallet_address(author_address)

    seq_num = p_data.get("sequence_number", 0)
    prev_hash = p_data.get("prev_post_hash", "")
    published_at = _to_naive_utc(
        p_data.get("published_at", datetime.now(timezone.utc))
    )
    source_type = p_data.get("source_type", "native")

    is_verified = True

    if check_chain and seq_num > 0 and author_address:
        stmt_last = select(Post).where(Post.author_address == author_address).order_by(desc(Post.sequence_number))
        last_known_post = (await db.execute(stmt_last)).scalars().first()
        
        if last_known_post:
            if last_known_post.hash_id != prev_hash:
                logger.warning(f"⚠️ Розрив ланцюжка для {author_address}. Очікували: {last_known_post.hash_id}, отримали: {prev_hash}")
                is_verified = False
                
                try:
                    async with httpx.AsyncClient() as client:
                        rust_fetch_url = RUST_CORE_URL.replace("/local/publish", f"/local/fetch_hash/{prev_hash}")
                        res = await client.get(rust_fetch_url, timeout=10.0)
                        
                        if res.status_code == 200 and res.json():
                            missing_data = res.json()
                            missing_p_data = {
                                "title": missing_data.get("title"),
                                "text_content": missing_data.get("text_preview", ""),
                                "content_size": missing_data.get("content_size", 0),
                                "is_full_content_loaded": False,
                                "author_address": missing_data.get("author_address"),
                                "hash_id": missing_data.get("hash_id"),
                                "content_blob_hash": missing_data.get("content_blob_hash"),
                                "prev_post_hash": missing_data.get("prev_post_hash", ""),
                                "sequence_number": missing_data.get("sequence_number", 0),
                                "signature": missing_data.get("signature"),
                                "source_type": "p2p_relay",
                                "published_at": datetime.fromtimestamp(missing_data.get("timestamp", 0), timezone.utc)
                            }
                            await process_incoming_post(db, missing_p_data, check_chain=False)
                            is_verified = True
                except Exception as e:
                    logger.error(f"Помилка синхронізації пропущеного поста: {e}")
        else:
            is_verified = False

    if seq_num > 0:
        stmt = select(Post).where(
            Post.author_address == author_address,
            Post.hash_id == prev_hash
        )
        
        existing_post = (await db.execute(stmt)).scalars().first()
        if existing_post:
            now_ts = datetime.now(timezone.utc).timestamp()
            pub_ts = _to_naive_utc(existing_post.published_at).replace(
                tzinfo=timezone.utc
            ).timestamp()
            
            if (now_ts - pub_ts) > 900 or existing_post.is_finalized:
                return None
                
            if source_type != "nostr":
                existing_post.text_content = ""
                existing_post.title = ""
            else:
                existing_post.text_content = p_data["text_content"]
                existing_post.title = p_data.get("title", "")
            existing_post.prev_post_hash = prev_hash
            existing_post.hash_id = p_data["hash_id"]
            existing_post.sequence_number = seq_num
            existing_post.signature = p_data["signature"]
            existing_post.is_verified = is_verified
            meta = p_data.get("metadata_", {}) or {}
            mime = meta.get("media_mime_type")
            if mime:
                if mime.startswith("video/"):
                    existing_post.content_type = ContentType.VIDEO
                elif mime.startswith("image/"):
                    existing_post.content_type = ContentType.IMAGE
                else:
                    existing_post.content_type = ContentType.TEXT
            return existing_post

    content_blob_hash = p_data.get("content_blob_hash")
    if not content_blob_hash:
        content_blob_hash = generate_content_hash(p_data["text_content"])

    stmt_exact = select(Post).where(Post.content_blob_hash == content_blob_hash).order_by(Post.published_at).limit(1)
    exact_match = (await db.execute(stmt_exact)).scalars().first()

    parent_id = None
    is_repost = False

    if exact_match:
        parent_id = exact_match.parent_post_id or exact_match.id
        is_repost = True
    else:
        parent_hash = await brain.find_duplicate_async(p_data["text_content"], threshold=0.95, hours=24)
        if parent_hash:
            stmt_parent = select(Post.id).where(Post.hash_id == parent_hash)
            parent_id = (await db.execute(stmt_parent)).scalar_one_or_none()
            is_repost = bool(parent_id)
        else:
            parent_id = None
            is_repost = False
            
    if isinstance(parent_id, str):
        if parent_id.isdigit():
            parent_id = int(parent_id)
        else:
            stmt_fix = select(Post.id).where(Post.hash_id == parent_id)
            parent_id = (await db.execute(stmt_fix)).scalar_one_or_none()

    meta_for_type = p_data.get("metadata_", {}) or {}
    mime = meta_for_type.get("media_mime_type")
    if mime:
        if mime.startswith("video/"):
            content_type_val = ContentType.VIDEO
        else:
            content_type_val = ContentType.TEXT
    else:
        content_type_val = ContentType.TEXT

    new_post = Post(
        source_type=source_type,
        source_specific_id=p_data.get("source_specific_id"),
        title=p_data.get("title", "") if source_type == "nostr" else "", 
        text_content=p_data["text_content"] if source_type == "nostr" else "",
        content_size=p_data.get("content_size", len(p_data["text_content"].encode('utf-8'))),
        is_full_content_loaded=p_data.get("is_full_content_loaded", True),
        author_address=author_address,
        original_author_name=p_data.get("original_author_name"),
        external_link=p_data.get("external_link"),
        published_at=published_at,
        hash_id=p_data.get("hash_id"),
        content_blob_hash=content_blob_hash,
        prev_post_hash=prev_hash,
        sequence_number=seq_num,
        signature=p_data.get("signature"),
        parent_post_id=parent_id,
        is_verified=is_verified,
        is_repost=is_repost,
        metadata_=p_data.get("metadata_", {}),
        content_type=content_type_val,
        language=p_data.get("language", "")
    )
    
    if not new_post.language and p_data.get("text_content") and len(p_data["text_content"].strip()) > 5:
        try:
            from langdetect import detect
            new_post.language = detect(p_data["text_content"])
        except Exception:
            new_post.language = "uk" # fallback
            
    # Save language to metadata_
    if new_post.language:
        meta_dict = dict(new_post.metadata_ or {})
        meta_dict["language"] = new_post.language
        new_post.metadata_ = meta_dict
    
    db.add(new_post)
    await db.flush()
    
    if not parent_id and not exact_match and source_type != "media_blob":
        lang = new_post.language or ""
        geo = (p_data.get("metadata_") or {}).get("geo", "")
        asyncio.create_task(_background_add_vector(new_post.id, new_post.hash_id, p_data["text_content"], source_type, language=lang, geo=geo))
        
        if author_address and len(p_data.get("text_content", "")) > 50:
            import hashlib
            from models import CreditTransaction
            tx_hash = hashlib.sha256(f"POUW:{new_post.hash_id}:{author_address}".encode()).hexdigest()
            
            if p2p:
                payload = {
                    "type": "pbft_propose",
                    "tx_hash": tx_hash,
                    "wallet_address": author_address,
                    "amount": 1,
                    "reason": "Proof of Useful Work (Unique Content)",
                    "signature": "node_signature_placeholder",
                }
                try:
                    await p2p.publish_message(payload)
                    logger.info(f"Proposed 1 credit for {author_address} (POUW)")
                except Exception as e:
                    logger.error(f"Failed to propose PBFT credit: {e}")

    
    return new_post





class CreatePostRequest(BaseModel):
    author_address: str 
    title: str | None = None 
    text_content: str
    hash_id: str
    prev_post_hash: str = ""
    sequence_number: int = 0
    signature: str      
    pow_nonce: int | None = None

@app.post("/local/publish")
async def proxy_local_publish(request: Request, db: AsyncSession = Depends(get_db)):
    payload = await request.json()

    # Cryptographic Handshake (Client-to-Node)
    author = payload.get("author") or payload.get("author_address")
    hash_id = payload.get("hash_id")
    signature = payload.get("signature")
    if not author or not hash_id or not signature:
        raise HTTPException(status_code=400, detail="Missing author, hash_id, or signature")
    
    if not verify_signature(hash_id, signature, author):
        raise HTTPException(status_code=401, detail="Invalid cryptographic signature")

    # PoW Protection for new users
    author_clean = _normalize_wallet_address(author)
    stmt = select(User).where(User.wallet_address == author_clean)
    user = (await db.execute(stmt)).scalar_one_or_none()
    
    if not user or user.indexed_posts_count == 0:
        pow_nonce = payload.get("pow_nonce")
        if pow_nonce is None:
            raise HTTPException(status_code=400, detail="pow_nonce required for first post")
        import hashlib
        challenge = f"{hash_id}{pow_nonce}".encode('utf-8')
        pow_hash = hashlib.sha256(challenge).hexdigest()
        if not pow_hash.startswith("0000"):
            raise HTTPException(status_code=400, detail="Invalid PoW. Hash must start with 4 zeros.")

    try:
        from datetime import datetime, timezone
        
        p_data = {
            "title": payload.get("title"),
            "text_content": payload["text"],
            "content_size": len(payload["text"].encode('utf-8')),
            "is_full_content_loaded": True,
            "author_address": payload.get("author") or payload.get("author_address"),
            "hash_id": payload["hash_id"],
            "content_blob_hash": payload.get("content_blob_hash"),
            "prev_post_hash": payload.get("prev_post_hash", ""),
            "sequence_number": payload.get("sequence_number", 0),
            "signature": payload.get("signature"),
            "source_type": payload.get("source_type", "native"),
            "metadata_": payload.get("metadata_", {}),
            "original_author_name": None,
            "published_at": datetime.now(timezone.utc)
        }
        
        saved_post = await process_incoming_post(db, p_data, check_chain=True)
        if not saved_post:
            raise HTTPException(status_code=400, detail="Failed to process post locally")
            
        pb_req = feedo_pb2.PublishRequest(
            text=payload["text"],
            author=payload["author"],
            signature=payload["signature"],
            hash_id=payload["hash_id"],
            content_blob_hash=payload.get("content_blob_hash", ""),
            prev_post_hash=payload.get("prev_post_hash", ""),
            sequence_number=payload.get("sequence_number", 0),
            skip_dht_upload=payload.get("skip_dht_upload", False),
            title=payload.get("title", ""),
            source_type=payload.get("source_type", ""),
            metadata=_json.dumps(payload.get("metadata_", {})),
            pow_nonce=payload.get("pow_nonce", 0)
        )
        
        async with httpx.AsyncClient() as client:
            response = await client.post(
                RUST_CORE_URL, 
                content=pb_req.SerializeToString(), 
                headers={"Content-Type": "application/x-protobuf"},
                timeout=15.0
            )
            
        return {
            "status": "published",
            "post": await _serialize_post_for_client(db, saved_post),
            "message": response.text if response.status_code not in (200, 201) else "Successfully broadcasted"
        }
    except Exception as e:
        logger.error(f"Failed to publish: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/posts/by-client/{client_id}")
async def get_post_by_client_id(client_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(Post).where(Post.metadata_.contains({"client_id": client_id}))
    post = (await db.execute(stmt)).scalars().first()
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return await _serialize_post_for_client(db, post)


@app.get("/posts/by-hash/{hash_id}")
async def get_post_by_hash_id(hash_id: str, db: AsyncSession = Depends(get_db)):
    stmt = select(Post).where(Post.hash_id == hash_id)
    post = (await db.execute(stmt)).scalars().first()
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return await _serialize_post_for_client(db, post)


@app.get("/posts/{post_id}")
async def get_post_by_id(post_id: int, db: AsyncSession = Depends(get_db)):
    stmt = select(Post).where(Post.id == post_id)
    post = (await db.execute(stmt)).scalars().first()
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return await _serialize_post_for_client(db, post)


@app.post("/local/upload_media")
async def proxy_local_upload_media(file: UploadFile = File(...), db: AsyncSession = Depends(get_db)):
    file_data = await file.read()
    rust_upload_url = RUST_CORE_URL.replace("/local/publish", "/local/upload_media")

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                rust_upload_url,
                files={"file": (file.filename or "attachment", file_data, file.content_type or "application/octet-stream")},
                timeout=60.0,
            )

        if response.status_code in (200, 201):
            try:
                payload = response.json()
                media_hash = payload.get("media_hash")
                media_size = payload.get("size", len(file_data))
                if media_hash:
                    # populate in-memory cache so the media can be served immediately
                    try:
                        MEDIA_CACHE[media_hash] = {
                            "bytes": file_data,
                            "mime": file.content_type or "application/octet-stream",
                            "size": len(file_data),
                        }
                        _store_media_to_disk_cache(media_hash, file_data)
                    except Exception:
                        logger.warning("Failed to populate MEDIA_CACHE for %s", media_hash)

                    existing_media = (
                        await db.execute(
                            select(Post).where(Post.content_blob_hash == media_hash).limit(1)
                        )
                    ).scalars().first()
                    if not existing_media:
                        media_b64_text = base64.b64encode(file_data).decode("utf-8")
                        media_meta = {
                            "media_name": file.filename or "attachment",
                            "media_mime_type": file.content_type or "application/octet-stream",
                            "media_size": len(file_data),
                            "media_b64_size": len(media_b64_text.encode("utf-8")),
                        }
                        db.add(
                            Post(
                                source_type="media_blob",
                                text_content="",
                                content_size=len(media_b64_text.encode("utf-8")),
                                is_full_content_loaded=False,
                                author_address="network_sync",
                                content_blob_hash=media_hash,
                                hash_id=media_hash,
                                metadata_=media_meta,
                                content_type=ContentType.IMAGE,
                            )
                        )
                        await db.commit()
            except Exception as cache_error:
                logger.warning(f"Failed to cache uploaded media locally: {cache_error}")
        # If rust returned JSON, merge and return helpful info (but keep original response when not JSON)
        try:
            rust_json = response.json()
            # Attach a hint that the API has the raw base64 available via /p2p-media immediately
            rust_json.setdefault("immediate_url", f"/p2p-media/{rust_json.get('media_hash')}")
            return Response(content=_json.dumps(rust_json), status_code=response.status_code, media_type="application/json")
        except Exception:
            return Response(
                content=response.text,
                status_code=response.status_code,
                media_type=response.headers.get("content-type", "text/plain; charset=utf-8"),
            )
    except httpx.RequestError as e:
        raise HTTPException(status_code=502, detail=f"Failed to reach Rust core: {e}")

class MarkBroadcastedRequest(BaseModel):
    hash_ids: list[str]
    relay_urls: list[str]

@app.get("/internal/nostr/pending_broadcasts", tags=["Internal"])
async def internal_nostr_pending_broadcasts(db: AsyncSession = Depends(get_db)):
    """Returns posts with source_type='nostr' that haven't been broadcasted to global relays yet."""
    stmt = select(Post).where(
        Post.source_type == "nostr",
        Post.relay_url == None
    ).order_by(Post.published_at.desc()).limit(50)
    
    posts = (await db.execute(stmt)).scalars().all()
    
    result = []
    for p in posts:
        metadata = p.metadata_ or {}
        if isinstance(metadata, str):
            import json
            try:
                metadata = json.loads(metadata)
            except:
                metadata = {}
                
        result.append({
            "hash_id": p.hash_id,
            "text": p.text_content,
            "author": p.author_address,
            "signature": p.signature,
            "metadata_": metadata
        })
    return {"posts": result}

@app.post("/internal/nostr/mark_broadcasted", tags=["Internal"])
async def internal_nostr_mark_broadcasted(req: MarkBroadcastedRequest, db: AsyncSession = Depends(get_db)):
    """Updates the relay_url field for posts that were successfully broadcasted."""
    if not req.hash_ids or not req.relay_urls:
        return {"status": "ok"}
        
    relays_str = ",".join(req.relay_urls)
    
    stmt = select(Post).where(Post.hash_id.in_(req.hash_ids))
    posts = (await db.execute(stmt)).scalars().all()
    
    for p in posts:
        # Після успішної відправки видаляємо текст!
        p.text_content = ""
        p.title = ""
        
        if p.relay_url:
            existing = p.relay_url.split(",")
            all_relays = list(set(existing + req.relay_urls))
            p.relay_url = ",".join(all_relays)
        else:
            p.relay_url = relays_str
            
    await db.commit()
    return {"status": "updated", "count": len(posts)}

ACTIVE_NETWORK_PEERS = {}

@app.post("/internal/p2p/register_peer")
async def register_peer(request: Request):
    data = await request.json()
    pubkey = data.get("pubkey_hex")
    api_url = data.get("api_url")
    timestamp = data.get("timestamp")
    sig = data.get("sig")
    
    if pubkey and api_url and sig:
        ACTIVE_NETWORK_PEERS[pubkey] = {
            "pubkey": pubkey,
            "api_url": api_url,
            "timestamp": timestamp,
            "sig": sig
        }
    return {"status": "ok"}

@app.get("/api/v1/network/peers")
async def get_network_peers():
    return list(ACTIVE_NETWORK_PEERS.values())

@app.post("/internal/p2p_receive")
async def receive_from_p2p(request: Request, db: AsyncSession = Depends(get_db)):
    data = await request.json()
    
    metadata = data.get("metadata_", {}) or {}
    metadata["p2p_timestamp"] = data.get("timestamp")

    p_data = {
        "title": data.get("title"), 
        "text_content": data.get("text_preview", ""),
        "content_size": data.get("content_size", 0),
        "is_full_content_loaded": False,
        "author_address": data.get("author_address"),
        "hash_id": data.get("hash_id") or data.get("content_hash"),
        "content_blob_hash": data.get("content_blob_hash"),
        "prev_post_hash": data.get("prev_post_hash", ""),
        "sequence_number": data.get("sequence_number", 0),
        "signature": data.get("signature"),
        "source_type": data.get("source_type") or "p2p_relay",
        "metadata_": metadata
    }
    
    post = await process_incoming_post(db, p_data)
    if post:
        try:
            await db.commit()
            return {"status": "saved", "id": post.id}
        except Exception as e:
            await db.rollback()
            logger.error(f"Помилка збереження P2P поста: {e}")
            
    return {"status": "ignored"}

class VectorQueryRequest(BaseModel):
    vector: List[float]
    k: int = 50
    threshold: float = 0.5

class BatchVectorQueryRequest(BaseModel):
    vectors: List[List[float]]
    k: int = 50
    threshold: float = 0.5

@app.post("/internal/vector/query")
async def vector_query(req: VectorQueryRequest, request: Request, api_key = Depends(get_api_key)):
    if not EXPOSE_VECTOR_API:
        raise HTTPException(status_code=403, detail="Vector API not exposed")
        
    pubkey = request.headers.get("X-P2P-Pubkey")
    if pubkey and p2p and hasattr(p2p, "reputation"):
        p2p.reputation.charge_peer(pubkey, req.k)
        p2p.reputation.can_afford(pubkey, req.k)

        
    k_limit = getattr(request.state, "k_limit", 20)
    actual_k = min(req.k, k_limit)
    VECTOR_QUERIES.labels(role=request.state.role.value, status="success").inc()
    
    results = []
    if brain:
        try:
            res = brain.table.search(req.vector).limit(actual_k).to_list()
            post_ids = [r["post_id"] for r in res if "hash_id" not in r]
            id_to_hash = {}
            if post_ids:
                async with AsyncSessionLocal() as db:
                    stmt = select(Post.id, Post.hash_id).where(Post.id.in_(post_ids))
                    post_rows = (await db.execute(stmt)).all()
                    id_to_hash = {row.id: row.hash_id for row in post_rows}
            
            seen_hashes = set()
            for r in res:
                similarity = 1.0 - (r["_distance"] / 2.0)
                if similarity >= req.threshold:
                    h_id = r.get("hash_id") or id_to_hash.get(r["post_id"])
                    if h_id and h_id not in seen_hashes:
                        seen_hashes.add(h_id)
                        results.append({"hash_id": h_id, "score": similarity})
        except Exception as e:
            logger.error(f"Vector query error: {e}")
            VECTOR_QUERIES.labels(role=request.state.role.value, status="error").inc()
            raise HTTPException(status_code=500, detail=str(e))
    return results

@app.post("/internal/vector/batch_query")
async def vector_batch_query(req: BatchVectorQueryRequest, request: Request, api_key = Depends(get_api_key)):
    if not EXPOSE_VECTOR_API:
        raise HTTPException(status_code=403, detail="Vector API not exposed")
        
    if request.state.role == ApiKeyRole.ANONYMOUS:
        raise HTTPException(status_code=403, detail="Batch query not allowed for anonymous users")
        
    pubkey = request.headers.get("X-P2P-Pubkey")
    if pubkey and p2p and hasattr(p2p, "reputation"):
        p2p.reputation.charge_peer(pubkey, len(req.vectors) * req.k)
        p2p.reputation.can_afford(pubkey, len(req.vectors) * req.k)
        
    if len(req.vectors) > 50:
        raise HTTPException(status_code=400, detail="Max 50 vectors per batch")
        
    k_limit = getattr(request.state, "k_limit", 20)
    actual_k = min(req.k, k_limit)
    VECTOR_QUERIES.labels(role=request.state.role.value, status="success").inc(len(req.vectors))
    
    batch_results = []
    if brain:
        try:
            for vec in req.vectors:
                res = brain.table.search(vec).limit(actual_k).to_list()
                local_res = []
                seen_hashes = set()
                for r in res:
                    similarity = 1.0 - (r["_distance"] / 2.0)
                    if similarity >= req.threshold:
                        h_id = r.get("hash_id")
                        if h_id and h_id not in seen_hashes:
                            seen_hashes.add(h_id)
                            local_res.append({"hash_id": h_id, "score": similarity})
                batch_results.append(local_res)
        except Exception as e:
            logger.error(f"Vector batch query error: {e}")
            VECTOR_QUERIES.labels(role=request.state.role.value, status="error").inc()
            raise HTTPException(status_code=500, detail=str(e))
    return batch_results

@app.get("/internal/vector/by_post/{hash_id}")
async def vector_by_post(hash_id: str, request: Request, db: AsyncSession = Depends(get_db), api_key = Depends(get_api_key)):
    if not EXPOSE_VECTOR_API:
        raise HTTPException(status_code=403, detail="Vector API not exposed")
        
    pubkey = request.headers.get("X-P2P-Pubkey")
    if pubkey and p2p and hasattr(p2p, "reputation"):
        p2p.reputation.charge_peer(pubkey, 1)
        p2p.reputation.can_afford(pubkey, 1)
        
    if brain:
        try:
            res = brain.table.search().where(f"hash_id = '{hash_id}'").limit(1).to_list()
            if res:
                return {"hash_id": hash_id, "vector": res[0]["vector"], "timestamp": res[0]["timestamp"]}
        except Exception:
            pass
            
    stmt = select(Post.id).where(Post.hash_id == hash_id)
    post_id = (await db.execute(stmt)).scalar_one_or_none()
    if not post_id:
        raise HTTPException(status_code=404, detail="Post not found locally")
        
    if brain:
        res = brain.table.search().where(f"post_id = {post_id}").limit(1).to_list()
        if res:
            return {"hash_id": hash_id, "vector": res[0]["vector"], "timestamp": res[0]["timestamp"]}
            
    raise HTTPException(status_code=404, detail="Vector not found")

@app.get("/internal/vector/recent")
async def vector_recent(request: Request, since: float = 0.0, limit: int = 100, db: AsyncSession = Depends(get_db), api_key = Depends(get_api_key)):
    if not EXPOSE_VECTOR_API:
        raise HTTPException(status_code=403, detail="Vector API not exposed")
        
    pubkey = request.headers.get("X-P2P-Pubkey")
    if pubkey and p2p and hasattr(p2p, "reputation"):
        p2p.reputation.charge_peer(pubkey, 1)
        p2p.reputation.can_afford(pubkey, 1)
        
    if request.state.role == ApiKeyRole.ANONYMOUS:
        actual_limit = min(limit, 20)
    else:
        actual_limit = min(limit, 500)
        
    stmt = select(Post.hash_id).where(Post.parent_post_id == None)
    if since > 0.0:
        dt = datetime.fromtimestamp(since, tz=timezone.utc).replace(tzinfo=None)
        stmt = stmt.where(Post.published_at > dt)
    stmt = stmt.order_by(desc(Post.published_at)).limit(actual_limit)
    res = (await db.execute(stmt)).scalars().all()
    return {"recent_hash_ids": list(res)}

@app.get("/internal/vector/metadata/{hash_id}")
async def vector_metadata(hash_id: str, request: Request, db: AsyncSession = Depends(get_db), api_key = Depends(get_api_key)):
    if not EXPOSE_VECTOR_API:
        raise HTTPException(status_code=403, detail="Vector API not exposed")
        
    stmt = select(Post).where(Post.hash_id == hash_id)
    post = (await db.execute(stmt)).scalar_one_or_none()
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
        
    if request.state.role == ApiKeyRole.ANONYMOUS:
        return {
            "hash_id": post.hash_id,
            "content_size": post.content_size
        }
        
    return {
        "hash_id": post.hash_id,
        "content_size": post.content_size,
        "text_preview": post.text_content[:200] + "..." if len(post.text_content) > 200 else post.text_content,
        "author_address": post.author_address,
        "published_at": post.published_at.isoformat(),
        "source_type": post.source_type
    }

@app.get("/metrics")
async def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

@app.get("/internal/vector/health")
async def vector_health():
    return {"status": "ok", "vector_api_exposed": EXPOSE_VECTOR_API, "brain_loaded": brain is not None}

@app.get("/posts/{hash_id}/load_full")
async def load_full_content(hash_id: str, db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    stmt = select(Post).where(Post.hash_id == hash_id)
    post = (await db.execute(stmt)).scalars().first()
    
    if not post: 
        raise HTTPException(status_code=404, detail="Post not found")
        
    if post.is_full_content_loaded: 
        return {"content": post.text_content}
    
    try:
        async with httpx.AsyncClient() as client:
            res = await client.get(f"{RUST_FETCH_CONTENT_URL}/{post.content_blob_hash}/{post.content_size}", timeout=60.0)
            full_content = res.json()
            
            if full_content:
                post.text_content = full_content
                post.is_full_content_loaded = True
                await db.commit()
                return {"content": full_content}
            else:
                raise HTTPException(status_code=404, detail="Мережа не змогла зібрати 30/45 шархів.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/feed")
async def get_feed(limit: int = 50, offset: int = 0, source_type: str = "main", language: str | None = Query(None), text: str | None = Query(None), wallet_address: str | None = None, request: Request = None, db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    if request:
        pubkey = request.headers.get("X-P2P-Pubkey")
        if pubkey and hasattr(p2p, "reputation"):
            p2p.reputation.charge_peer(pubkey, limit)
            p2p.reputation.can_afford(pubkey, limit)

    user = None
    if wallet_address:
        user = (await db.execute(select(User).where(User.wallet_address == wallet_address))).scalar_one_or_none()
    
    from services.feed_service import FeedService
    scored_posts, rel_hash_ids, disc_hash_ids, rand_res = await FeedService.generate_feed(
        db=db,
        brain=brain,
        limit=limit,
        offset=offset,
        source_type=source_type,
        language=language,
        text=text,
        user=user,
        expose_vector_api=EXPOSE_VECTOR_API,
        vector_api_addr=VECTOR_API_ADDR,
        vector_api_key=VECTOR_API_KEY
    )
    
    feed_response = []
    additional_perspective_posts = []
    
    rel_hash_id_set = set(rel_hash_ids)
    disc_hash_id_set = set(disc_hash_ids)
    rand_res_set = set(rand_res) if 'rand_res' in locals() else set()
    
    for score, p in scored_posts:
        # Use centralized serialization which handles JSON parsing for profiles, avatars, etc.
        post_dict = await _serialize_post_for_client(db, p)
        
        # Filter out garbage Nostr events from the main feed (e.g. kind 4 DMs, kind 9735 Zaps, kind 0 Profiles)
        metadata = post_dict.get("metadata") or {}
        if isinstance(metadata, dict) and post_dict.get("source_type") == "nostr":
            kind = metadata.get("kind")
            if kind is not None and kind not in (1, 6): # Only show standard text notes and reposts
                continue
                
        reason = None
        if wallet_address and post_dict["is_repost"] and post_dict["author_address"] == wallet_address:
            reason = "Duplicate"
        elif post_dict["hash_id"] in rel_hash_id_set:
            reason = "За вашими інтересами"
        elif post_dict["hash_id"] in disc_hash_id_set:
            reason = "Anti-bubble"
        elif post_dict["id"] in rand_res_set:
            reason = "Random discovery"
            
        post_dict["recommendation_reason"] = reason
        feed_response.append(post_dict)
        
        dup_count = len(p.duplicates)
        perspectives_to_add = 0
        if dup_count > 4: perspectives_to_add = 1
        if dup_count >= 15: perspectives_to_add = 2
        if dup_count >= 30: perspectives_to_add = 4
        if dup_count >= 50: perspectives_to_add = 5
        if dup_count >= 100: perspectives_to_add = 7
        
        if perspectives_to_add > 0:
            available_dups = list(p.duplicates)
            random.shuffle(available_dups)
            added = 0
            for rand_dup in available_dups:
                if added >= perspectives_to_add:
                    break
                    
                if p.text_content and rand_dup.text_content:
                    similarity = difflib.SequenceMatcher(None, p.text_content, rand_dup.text_content).ratio()
                    if similarity > 0.85:
                        continue
                        
                dup_author = rand_dup.original_author_name if rand_dup.original_author_name else _display_author_name(rand_dup.author, rand_dup.author_address)
                dup_dict = dict(post_dict)
                dup_dict["id"] = rand_dup.id
                dup_dict["text"] = rand_dup.text_content
                dup_dict["display_author"] = dup_author
                dup_dict["author_address"] = rand_dup.author_address
                dup_dict["avatar_url"] = f"/p2p-media/{rand_dup.author.avatar_media_hash}" if rand_dup.author and rand_dup.author.avatar_media_hash else None
                dup_dict["recommendation_reason"] = "Інша думка на цю тему"
                
                copy_also_posted = []
                orig_author = p.original_author_name if p.original_author_name else _display_author_name(p.author, p.author_address)
                copy_also_posted.append({
                    "id": p.id,
                    "source_type": p.source_type,
                    "link": p.external_link,
                    "published_at": p.published_at,
                    "metadata": p.metadata_,
                    "text": p.text_content,
                    "display_author": orig_author,
                    "author_address": p.author_address,
                    "avatar_url": f"/p2p-media/{p.author.avatar_media_hash}" if p.author and p.author.avatar_media_hash else None,
                    "is_repost": p.is_repost,
                })
                for dup_info in post_dict["also_posted_by"]:
                    if dup_info["id"] != rand_dup.id:
                        copy_also_posted.append(dup_info)
                        
                dup_dict["also_posted_by"] = copy_also_posted
                additional_perspective_posts.append((dup_dict, p.id))
                added += 1

    for ap, orig_id in additional_perspective_posts:
        orig_idx = next((i for i, item in enumerate(feed_response) if item["id"] == orig_id), 0)
        min_insert_idx = orig_idx + 1
        
        if min_insert_idx < len(feed_response):
            insert_idx = random.randint(min_insert_idx, len(feed_response))
        else:
            insert_idx = len(feed_response)
            
        feed_response.insert(insert_idx, ap)

    return feed_response


 
class DeletePostRequest(BaseModel):
    wallet_address: str
    post_id: int
    timestamp: int
    signature: str


@app.post("/posts/delete")
async def delete_post(req: DeletePostRequest, db: AsyncSession = Depends(get_db)):
    validate_zero_trust_request(
        wallet_address=req.wallet_address,
        timestamp=req.timestamp,
        payload_dict={"post_id": req.post_id},
        signature=req.signature
    )
    
    stmt = select(Post).where(Post.id == req.post_id)
    post = (await db.execute(stmt)).scalar_one_or_none()
    if not post:
        raise HTTPException(status_code=404, detail="Пост не знайдено")
        
    post_author = post.author_address or ""
    req_author = req.wallet_address
    if post_author.startswith("0x"): post_author = post_author[2:]
    if req_author.startswith("0x"): req_author = req_author[2:]
    if post_author.lower() != req_author.lower():
        raise HTTPException(status_code=403, detail="Ви не є автором цього поста")
        
    now_ts = datetime.now(timezone.utc).timestamp()
    pub_ts = _to_naive_utc(post.published_at).replace(tzinfo=timezone.utc).timestamp()
    if (now_ts - pub_ts) > 900:
        raise HTTPException(status_code=400, detail="Час для видалення поста (15 хвилин) закінчився")
        
    if post.is_finalized:
        raise HTTPException(status_code=400, detail="Цей пост вже фіналізовано в блокчейні і його не можна видалити")
        
    await db.delete(post)
    await db.commit()
    return {"status": "success", "message": "Пост видалено"}




@app.get("/p2p-media/{media_hash}")
async def get_p2p_media(media_hash: str, size: int | None = None, db: AsyncSession = Depends(get_db)):
    try:
        cached = MEDIA_CACHE.get(media_hash)
        if cached is not None:
            try:
                return Response(content=cached["bytes"], media_type=cached.get("mime", "application/octet-stream"), status_code=200)
            except Exception:
                pass

        disk_cached = _load_media_from_disk_cache(media_hash)
        if disk_cached is not None:
            try:
                media_type = "application/octet-stream"
                stmt = select(Post).where(Post.content_blob_hash == media_hash).limit(1)
                media_post = (await db.execute(stmt)).scalars().first()
                if media_post and media_post.metadata_:
                    media_type = media_post.metadata_.get("media_mime_type", media_type)
                MEDIA_CACHE[media_hash] = {
                    "bytes": disk_cached,
                    "mime": media_type,
                    "size": len(disk_cached),
                }
                return Response(content=disk_cached, media_type=media_type, status_code=200)
            except Exception:
                pass

        stmt = select(Post).where(Post.content_blob_hash == media_hash).limit(1)
        media_post = (await db.execute(stmt)).scalars().first()

        b64_content = None

        if media_post and media_post.is_full_content_loaded:
            b64_content = media_post.text_content
        else:
            media_meta = media_post.metadata_ if (media_post and isinstance(media_post.metadata_, dict)) else {}
            size_candidates: list[int] = []

        def _append_candidate(candidate: Any) -> None:
            if candidate is None:
                return
            try:
                parsed = int(candidate)
            except Exception:
                return
            if parsed <= 0:
                return
            if parsed not in size_candidates:
                size_candidates.append(parsed)

        _append_candidate(size)
        _append_candidate(media_meta.get("media_size") if isinstance(media_meta, dict) else None)
        _append_candidate(media_meta.get("media_b64_size") if isinstance(media_meta, dict) else None)
        if media_post is not None:
            _append_candidate(media_post.content_size)

        for candidate in list(size_candidates):
            inferred_raw = (candidate // 4) * 3
            inferred_b64 = ((candidate + 2) // 3) * 4
            _append_candidate(inferred_raw)
            _append_candidate(inferred_b64)

            if not size_candidates:
                raise HTTPException(status_code=404, detail="media unavailable")

        last_exc = None
        used_size: int | None = None
        for resolved_size in size_candidates:
            for fetch_base in RUST_FETCH_CONTENT_URLS:
                try:
                    async with httpx.AsyncClient() as client:
                        res = await client.get(f"{fetch_base.rstrip('/')}/{media_hash}/{resolved_size}", timeout=12.0)
                    if res.status_code == 200:
                        try:
                            b64_candidate = res.json()
                        except Exception:
                            b64_candidate = None
                        if b64_candidate:
                            b64_content = b64_candidate
                            used_size = resolved_size
                            break
                    elif res.status_code == 404:
                        last_exc = Exception(
                            f"Rust fetch returned 404 Not Found from {fetch_base} (size={resolved_size})"
                        )
                    else:
                        last_exc = Exception(
                            f"Rust fetch returned status {res.status_code} from {fetch_base} (size={resolved_size})"
                        )
                except Exception as e:
                    last_exc = Exception(f"{e} (fetch_base={fetch_base}, size={resolved_size})")
            if b64_content:
                break

            if last_exc is not None and b64_content is None and "404" not in str(last_exc):
                logger.warning(
                    "P2P media reconstruction failed for %s: %s (tried_sizes=%s)",
                    media_hash,
                    last_exc,
                    size_candidates,
                )
                raise HTTPException(status_code=404, detail="media unavailable")

            if not b64_content:
                raise HTTPException(status_code=404, detail="media unavailable")

            if not media_post:
                resolved_size = used_size or size_candidates[0]
                new_media = Post(
                    source_type="media_blob",
                    text_content="",
                    content_size=resolved_size,
                    is_full_content_loaded=False,
                    author_address="network_sync",
                    content_blob_hash=media_hash,
                    hash_id=f"sync_{media_hash}"
                )
                db.add(new_media)
                await db.commit()

        image_data = base64.b64decode(b64_content)
        mime_type = "application/octet-stream"
        if media_post and media_post.metadata_:
            mime_type = media_post.metadata_.get("media_mime_type", mime_type)
        else:
            stmt_parents = select(Post).where(Post.metadata_.isnot(None))
            res = (await db.execute(stmt_parents)).scalars().all()
            for p in res:
                md = p.metadata_ or {}
                if md.get("media_hash") == media_hash and md.get("media_mime_type"):
                    mime_type = md.get("media_mime_type")
                    break

        MEDIA_CACHE[media_hash] = {
            "bytes": image_data,
            "mime": mime_type,
            "size": len(image_data),
        }
        _store_media_to_disk_cache(media_hash, image_data)

        return Response(content=image_data, media_type=mime_type)
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Unexpected /p2p-media failure for %s: %s", media_hash, exc)
        raise HTTPException(status_code=404, detail="media unavailable")


@app.get('/posts/author/{wallet_address}')
async def get_posts_by_author(wallet_address: str, limit: int = 100, db: AsyncSession = Depends(get_db)):
    normalized_wallet = _normalize_wallet_address(wallet_address)
    stmt = select(Post).where(
        func.lower(Post.author_address) == normalized_wallet,
        Post.source_type != 'media_blob',
    ).order_by(desc(Post.published_at)).limit(limit)
    stmt = stmt.options(selectinload(Post.author), selectinload(Post.duplicates))
    result = await db.execute(stmt)
    posts = result.scalars().all()

    out = []
    for p in posts:
        author = p.author or await _load_user_by_wallet(db, p.author_address)
        display_author = p.original_author_name if p.original_author_name else _display_author_name(author, p.author_address)
        also_posted_by = []
        for dup in p.duplicates:
            dup_author = dup.author or await _load_user_by_wallet(db, dup.author_address)
            also_posted_by.append({
                "id": dup.id,
                "source_type": dup.source_type,
                "link": dup.external_link,
                "published_at": dup.published_at,
                "metadata": dup.metadata_
            })

        out.append({
            "id": p.id,
            "title": p.title,
            "hash_id": p.hash_id,
            "content_blob_hash": p.content_blob_hash,
            "author_address": p.author_address,
            "display_author": display_author,
            "source_type": p.source_type,
            "text": p.text_content,
            "content_size": p.content_size,
            "published_at": p.published_at,
            "is_full": p.is_full_content_loaded,
            "metadata": p.metadata_,
            "relay_urls": p.relay_url.split(',') if p.relay_url else [],
            "also_posted_by": also_posted_by,
            "avatar_url": f"/p2p-media/{author.avatar_media_hash}" if author and author.avatar_media_hash else None,
            "sequence_number": p.sequence_number
        })
    return out








@app.post("/users/upload_avatar")
async def upload_avatar(
    author_address: str = Form(...),
    signature: str = Form(...),
    hash_id: str = Form(...),
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db)
):
    author_address = author_address.strip() if author_address else ""
    hash_id = hash_id.strip() if hash_id else ""
    signature = signature.strip() if signature else ""

    stmt = select(User).where(User.wallet_address == author_address)
    user = (await db.execute(stmt)).scalar_one_or_none()
    if not user:
        raise HTTPException(status_code=404, detail="Користувача не знайдено")

    if not verify_signature(hash_id, signature, user.wallet_address):
        raise HTTPException(status_code=401, detail="Invalid signature!")

    max_media_bytes = 10 * 1024 * 1024
    content = await file.read()
    media_raw_size = len(content)
    if media_raw_size > max_media_bytes:
        raise HTTPException(status_code=400, detail="Максимум 10 МБ")

    b64_text = base64.b64encode(content).decode('utf-8')
    media_hash = generate_content_hash(b64_text)
    media_size = media_raw_size
    media_b64_size = len(b64_text.encode('utf-8'))
    media_name = file.filename
    media_mime_type = file.content_type

    stmt_media = select(Post).where(Post.content_blob_hash == media_hash)
    existing_media = (await db.execute(stmt_media)).scalars().first()

    media_meta = {
        "media_name": media_name,
        "media_mime_type": media_mime_type,
        "media_size": media_raw_size,
        "media_b64_size": media_b64_size,
    }

    if existing_media:
        existing_media.content_size = media_size
        existing_media.metadata_ = media_meta
        existing_media.author_address = author_address
        existing_media.content_type = ContentType.IMAGE
        existing_media.is_full_content_loaded = False
        existing_media.text_content = ""
        existing_media.content_blob_hash = media_hash
        existing_media.hash_id = media_hash
    else:
        media_post = Post(
            source_type="media_blob",
            text_content="",
            content_size=media_size,
            is_full_content_loaded=False,
            author_address=author_address,
            content_blob_hash=media_hash,
            hash_id=media_hash,
            metadata_=media_meta,
            content_type=ContentType.IMAGE,
        )
        db.add(media_post)

    await db.commit()

    try:
        async with httpx.AsyncClient() as client:
            import feedo_pb2
            pb_req = feedo_pb2.PublishRequest(
                text=b64_text,
                author=author_address,
                signature=signature,
                hash_id=media_hash,
                content_blob_hash=media_hash,
                prev_post_hash="",
                sequence_number=0,
                skip_dht_upload=False
            )
            await client.post(
                RUST_CORE_URL, 
                content=pb_req.SerializeToString(),
                headers={"Content-Type": "application/x-protobuf"},
                timeout=15.0
            )
    except Exception as e:
        logger.warning(f"Failed to seed media to DHT: {e}")

    try:
        MEDIA_CACHE[media_hash] = {
            "bytes": content,
            "mime": media_mime_type or "application/octet-stream",
            "size": media_raw_size,
        }
        _store_media_to_disk_cache(media_hash, content)
    except Exception:
        logger.warning("Failed to populate MEDIA_CACHE for avatar %s", media_hash)

    return {"status": "success", "media_hash": media_hash}

from media_storage import get_media_storage

@app.post("/e2ee/media/upload")
async def upload_encrypted_media(
    file: UploadFile = File(...)
):
    storage = get_media_storage()
    data = await file.read()
    media_id = await storage.upload(data, file.content_type)
    return {"status": "success", "media_id": media_id}

@app.get("/e2ee/media/download/{media_id}")
async def download_encrypted_media(media_id: str):
    storage = get_media_storage()
    data = await storage.download(media_id)
    if not data:
        raise HTTPException(status_code=404, detail="Media not found")
    return Response(content=data, media_type="application/octet-stream")

# --- Phase 2: Web3 Native Features ---

class EdgeCreateRequest(BaseModel):
    source_hash: str
    target_hash: str
    edge_type: str
    author_address: str
    signature: str

@app.post("/edges")
async def create_edge(req: EdgeCreateRequest, db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    
    from core.utils.crypto_utils import verify_signature
    msg = f"{req.source_hash}:{req.target_hash}:{req.edge_type}"

    
    edge = Edge(
        source_hash=req.source_hash,
        target_hash=req.target_hash,
        edge_type=req.edge_type,
        author_address=_normalize_wallet_address(req.author_address),
        signature=req.signature
    )
    db.add(edge)
    try:
        await db.commit()
    except Exception as e:
        await db.rollback()
        raise HTTPException(status_code=400, detail=str(e))
        
    if p2p:
        payload = {"type": "edge", "data": req.model_dump()}
        try:
            await p2p.publish_message(payload)
        except Exception:
            pass
            
    return {"status": "ok", "edge_id": edge.id}

@app.get("/edges/{post_hash}")
async def get_edges(post_hash: str, db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    stmt = select(Edge).where(or_(Edge.source_hash == post_hash, Edge.target_hash == post_hash))
    edges = (await db.execute(stmt)).scalars().all()
    return [{
        "id": e.id,
        "source_hash": e.source_hash,
        "target_hash": e.target_hash,
        "edge_type": e.edge_type,
        "author_address": e.author_address,
        "created_at": e.created_at
    } for e in edges]


@app.get("/query")
async def federated_query(text: str, limit: int = 10, offset: int = 0, federated: bool = False, item_type: str = "all", profile_search_by: str = "name", db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    
    if item_type == "profile":
        if profile_search_by == "name":
            cond = (
                (Post.metadata_["name"].as_string().ilike(f"%{text}%")) |
                (Post.metadata_["display_name"].as_string().ilike(f"%{text}%"))
            )
        elif profile_search_by == "id":
            cond = (Post.author_address.ilike(f"{text}%"))
        else: # both
            cond = (
                (Post.metadata_["name"].as_string().ilike(f"%{text}%")) |
                (Post.metadata_["display_name"].as_string().ilike(f"%{text}%")) |
                (Post.author_address == text)
            )
            
        stmt = select(Post).options(selectinload(Post.author), selectinload(Post.duplicates)).where(
            (Post.item_type == "profile") & cond
        ).limit(limit).offset(offset)
        posts = (await db.execute(stmt)).scalars().all()
        results = [await _serialize_post_for_client(db, p) for p in posts]
        return {"query_id": "profile_search", "results": results}

    if not brain:
        raise HTTPException(status_code=503, detail="Vector Brain not initialized")
        
    try:
        vector = await brain.get_embedding_async(text)
        try:
            # 1. Pseudo-Relevance Feedback: get top 3 closest items to capture contextual semantics
            pr_results = brain.table.search(vector).limit(3).to_list()
            pr_vectors = [r["vector"] for r in pr_results if "vector" in r]
            if pr_vectors:
                # Average the original vector (weight 0.6) with the retrieved vectors (weight 0.4 total)
                avg_retrieved = [sum(v[i] for v in pr_vectors) / len(pr_vectors) for i in range(len(vector))]
                vector = [0.6 * vector[i] + 0.4 * avg_retrieved[i] for i in range(len(vector))]
            
            # 2. Perform main search with pagination
            raw_results = brain.table.search(vector).limit(limit + offset).to_list()[offset:]
            rel_hash_ids = [r["hash_id"] for r in raw_results if "hash_id" in r and r.get("_distance", 0) < 1.6]
            
            # 3. Anti-Bubble Injection (only on first page to not mess up infinite scroll offsets)
            if offset == 0 and len(rel_hash_ids) >= 5:
                import random
                # Random vector to discover out-of-topic posts
                rand_vec = [random.uniform(-1, 1) for _ in range(len(vector))]
                discovery_results = brain.table.search(rand_vec).limit(3).to_list()
                disc_ids = [r["hash_id"] for r in discovery_results if "hash_id" in r and r["hash_id"] not in rel_hash_ids]
                # Inject anti-bubble posts randomly into the list
                for did in disc_ids:
                    insert_idx = random.randint(1, len(rel_hash_ids))
                    rel_hash_ids.insert(insert_idx, did)
                    
        except Exception as e:
            print(f"LanceDB query error: {e}")
            rel_hash_ids = []
        
        results = []
        if rel_hash_ids:
            stmt = select(Post).options(selectinload(Post.author), selectinload(Post.duplicates)).where(Post.hash_id.in_(rel_hash_ids))
            posts = (await db.execute(stmt)).scalars().all()
            
            # Sort posts to match the order of rel_hash_ids (most relevant first, with anti-bubble injected)
            post_map = {p.hash_id: p for p in posts}
            for hid in rel_hash_ids:
                if hid in post_map:
                    results.append(await _serialize_post_for_client(db, post_map[hid]))
        if federated:
            if p2p:
                peer_addrs = set()
                stmt_peers = select(Post.metadata_).where(Post.metadata_.is_not(None)).order_by(desc(Post.published_at)).limit(200)
                peer_metas = (await db.execute(stmt_peers)).scalars().all()
                for meta in peer_metas:
                    if isinstance(meta, dict) and "vector_api_addr" in meta:
                        addr = meta["vector_api_addr"]
                        if addr and addr != VECTOR_API_ADDR:
                            peer_addrs.add(addr)
                            
                async def fetch_peer(addr):
                    try:
                        async with httpx.AsyncClient() as client:
                            resp = await client.post(
                                f"{addr}/internal/vector/query",
                                json={"vector": vector, "k": limit, "threshold": 0.65},
                                timeout=1.0
                            )
                            if resp.status_code == 200:
                                return resp.json()
                    except Exception:
                        pass
                    return []
                    
                if peer_addrs:
                    tasks = [fetch_peer(addr) for addr in list(peer_addrs)[:5]]
                    peer_res = await asyncio.gather(*tasks)
                    remote_hids = set()
                    for pr in peer_res:
                        for item in pr:
                            remote_hids.add(item.get("hash_id"))
                            
                    if remote_hids:
                        stmt_rem = select(Post).where(Post.hash_id.in_(remote_hids))
                        rem_posts = (await db.execute(stmt_rem)).scalars().all()
                        for rp in rem_posts:
                            # Avoid duplicates
                            if not any(r["hash_id"] == rp.hash_id for r in results):
                                serialized = await _serialize_post_for_client(db, rp)
                                serialized["is_federated"] = True
                                results.append(serialized)
                                
        return {"query": text, "results": results}
    except Exception as e:
        logger.error(f"Federated Query error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


class MempoolValidationRequest(BaseModel):
    tx_hash: str
    originating_node: str
    text: str

@app.post("/local/validate_mempool_submission")
async def validate_mempool_submission(req: MempoolValidationRequest):
    _require_server_variant()
    try:
        brain = VectorBrain()
        duplicate_hash = await brain.find_duplicate_async(req.text, threshold=0.90)
        
        if duplicate_hash:
            logger.info(f"Mempool Submission {req.tx_hash} rejected: semantic_duplicate (similar to {duplicate_hash})")
            return {"valid": False, "reason": "semantic_duplicate"}
        
        logger.info(f"Mempool Submission {req.tx_hash} validated successfully")
        return {"valid": True}
    except Exception as e:
        logger.error(f"Validation error: {e}")
        return {"valid": False, "reason": str(e)}

class PbftCommitRequest(BaseModel):
    tx_hash: str
    status: str

@app.post("/internal/pbft_commit")
async def pbft_commit(req: PbftCommitRequest, db: AsyncSession = Depends(get_db)):
    _require_server_variant()
    if req.status != "finalized":
        return {"status": "ignored"}
    
    from models import CreditTransaction, CreditBalance
    
    stmt = select(CreditTransaction).where(CreditTransaction.tx_hash == req.tx_hash)
    existing = (await db.execute(stmt)).scalar_one_or_none()
    if existing:
        return {"status": "already_committed"}
        
    try:
        wallet = "unknown"
        tx_hash_str = req.tx_hash
        
        ctx = CreditTransaction(
            tx_hash=req.tx_hash,
            wallet_address=wallet,
            amount=1,
            reason="PBFT Finalized POUW",
            signature="pbft_consensus"
        )
        db.add(ctx)
        
        balance_stmt = select(CreditBalance).where(CreditBalance.wallet_address == wallet)
        balance = (await db.execute(balance_stmt)).scalar_one_or_none()
        if not balance:
            balance = CreditBalance(wallet_address=wallet, balance=1)
            db.add(balance)
        else:
            balance.balance += 1
            
        await db.commit()
    except Exception as e:
        await db.rollback()
        logger.error(f"PBFT commit failed: {e}")
        
    return {"status": "committed"}


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8040, reload=True)