const String developerDocsMarkdown = '''
# Feedo Protocol & Explorer Documentation

Welcome to the Feedo Explorer! Feedo has evolved into a robust decentralized protocol, functioning as a peer-to-peer (P2P) network for content aggregation, AI-driven vectorization, and data synchronization.

This Explorer is a dedicated, read-only interface connected to an isolated **Explorer Backend (Indexer)**. It is designed to visualize the real-time state of the network without overwhelming the core P2P nodes.

---

## 1. Core Architecture

The Feedo ecosystem now operates on a true Web3 foundation, eliminating centralized social network constraints:

*   **Decentralized Identifiers (DID) & Cryptography:** Every participant (peer) is identified by an ECDSA-based DID. All network interactions are cryptographically signed.
*   **Kademlia DHT & Gossipsub:** The core P2P layer leverages libp2p. Content is routed via Kademlia DHT, while rapid message dissemination relies on Gossipsub.
*   **CRDT Data Structures:** Conflict-free Replicated Data Types ensure that distributed graphs (posts, identities) eventually converge across all nodes without a central database.
*   **PBFT Consensus:** For critical state changes (like reputation updates or epoch transitions), the network employs Practical Byzantine Fault Tolerance (PBFT) among validator nodes.
*   **Data Availability (DA) via Supernodes:** High-capacity nodes (Supernodes) form a hierarchical layer responsible for ensuring large binary vectors and media remain available across the network.

---

## 2. Explorer Components

The newly redesigned Explorer provides critical insights into these layers:

### Network Topology
Monitors the live P2P network. It displays the total active peers and the subset of Supernodes that form the Data Availability Layer.

### Identities (DID)
Lists known network participants. Instead of traditional "User Profiles", you see cryptographic DIDs and their computed **Reputation Scores**. High reputation ensures prioritization during P2P syncing.

### Consensus Logs
A transparent ledger of network agreements. Here you can inspect the history of PBFT rounds, checking the hashes of confirmed blocks and distributed CRDT operations.

### Vector Space & Content Data
Allows developers to query raw content hashes and inspect the semantic embeddings (AI vectors) generated by the LanceDB integration. This is crucial for verifying that semantic search indexing is functioning properly across the swarm.

---

## 3. Developer Integration

If you are building dApps or integrating AI models using Feedo Data:

### Running an Independent Explorer
The Explorer Backend is completely decoupled from the Feedo Node API.
1. It runs a background `indexer.py` task.
2. It fetches network stats, DIDs, and consensus logs from the Node via HTTP/gRPC.
3. It serves cached, paginated data to this Flutter interface via `localhost:8001/api/v1`.

### Fetching Data for AI
To extract deduplicated, vectorized datasets:
1. Connect to a local Feedo Node using the `feedo_py` SDK.
2. Query the semantic space: `POST /internal/vector/batch_query`.
3. Resolve hashes into raw text via the DHT.

> **Note:** Heavy data consumption requires maintaining a positive DID Reputation. You must contribute bandwidth or unique data to the network to offset your consumption.

---

## 4. Getting Started Locally

To deploy the entire stack (Node + Explorer Backend + Frontend):

```bash
# 1. Start the core P2P Protocol Node
docker compose -f docker-compose.yml up -d

# 2. Start the Explorer Indexer Backend
docker compose -f docker-compose.explorer.yml up -d

# 3. Run this Flutter Frontend
cd feedo_explorer
flutter run -d web-server --web-port=8080
```

*For deeper protocol specifications, please refer to the `FEEDO_PROTOCOL.md` and `PROJECT_STRUCTURE.md` files located in the repository root.*
''';
