FROM itsshas/feedo-node:hybrid

# Оновлюємо лише Python-файли, які ми редагували сьогодні (Freemium, Proxy Fetching)
COPY feedo-api/ /app/
COPY feedo_parser/ /app/feedo_parser/
COPY start-hybrid.sh /app/start-hybrid.sh

# Вказуємо тип ноди
ENV NODE_TYPE=paragraph

CMD ["/app/start-hybrid.sh"]
