[package]
name = "feedo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53", features = ["macros", "tokio", "quic", "request-response", "cbor", "identify", "gossipsub", "kad", "mdns"] }
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prost = "0.12"
bytes = "1.5"
sha2 = "0.10"
axum = { version = "0.7", features = ["multipart", "ws"] }
futures = "0.3"
time = "=0.3.36"
reqwest = { version = "0.11", features = ["json", "blocking"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
reed-solomon-erasure = "6.0"
sled = "0.34"
secp256k1 = { version = "0.28", features = ["hashes"] }
hex = "0.4"
base64 = "0.22.1"
rand = "0.8"
tokio-tungstenite = { version = "0.20", optional = true }
tonic = { version = "0.11", optional = true }
rusqlite = { version = "0.31", features = ["bundled"] }
regex = "1.10"
ethers = "2.0"
rs_merkle = "1.4"

[features]
default = []
nostr = ["tokio-tungstenite"]
farcaster = ["tonic", "tonic-build"]

[[bin]]
name = "feedo-nostr"
path = "src/bin/feedo_nostr.rs"
required-features = ["nostr"]

[[bin]]
name = "feedo-farcaster"
path = "src/bin/feedo_farcaster.rs"
required-features = ["farcaster"]

[build-dependencies]
prost-build = "0.12"
tonic-build = { version = "0.11", optional = true }

[dev-dependencies]
rand = "0.8"
