name: Consensia Commit Review

on:
  push:
    branches:
      - main
      - 'feature/**' # Маска для відстеження фіча-гілок

permissions:
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 3 # Достатньо для порівняння поточного та попереднього коміту

      - name: Run Consensia AI Reviewer
        uses: Ashixi/consensia-action@main
        with:
          api-key: ${{ secrets.CONSENSIA_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: 'commit' # Вказуємо, що це прямий коміт
          mode: 'BALANCED'
